name: particle_game
description: "Particle Simulation Game"
publish_to: 'none'
version: 0.1.0+5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.28.1
  flutter_animate: ^4.5.2
  provider: ^6.1.5
  sprintf: ^7.0.0
  simple_sensor:
    git:
      url: https://github.com/AislingHeanue/simple_sensor.git
      ref: main
  material_symbols_icons: ^4.2815.1
  flutter_colorpicker: ^1.1.0
  wakelock_plus: 1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/app_icon.png"
